#!/bin/bash
EXAMPLEDIR=$1
EXAMPLE=${EXAMPLEDIR##*/}
. ./tools/scripts/set-env
EXAMPLE_UTILS_DIR=examples/utils/

# TODO: checking the existing of libgepard.so and geprd.h
./tools/scripts/build-gepard

mkdir -p $OUTDIR/$EXAMPLEDIR
g++ $GCC_GLOBAL_FLAGS -o $OUTDIR/$EXAMPLEDIR/$EXAMPLE $EXAMPLE_UTILS_DIR/*.cpp $EXAMPLEDIR/$EXAMPLE.cpp -I$INCDIR -I$SRCDIR -I$EXAMPLE_UTILS_DIR -L$LIBDIR -lgepard -lGLESv2 -lEGL -lX11
