#!/bin/bash
EXAMPLEDIR=$1
EXAMPLE=${EXAMPLEDIR##*/}
. ./tools/scripts/set-env

# TODO: checking the existing of libgepard.so and geprd.h
./tools/scripts/build-gepard

mkdir -p $OUTDIR/$EXAMPLEDIR
g++ $GCC_GLOBAL_FLAGS -o $OUTDIR/$EXAMPLEDIR/$EXAMPLE $EXAMPLEDIR/$EXAMPLE.cpp -I$INCDIR -L$LIBDIR -lgepard

