#!/bin/bash
EXAMPLEDIR=$1
EXAMPLE=${EXAMPLEDIR##*/}
. ./tools/scripts/set-env

# TODO: checking the existing EXAMPLE bin

export LD_LIBRARY_PATH="$LIBDIR:/usr/lib/nvidia-346"
./$OUTDIR/$EXAMPLEDIR/$EXAMPLE

