SET(GEPARD_DEP_LIBS "")
SET(GEPARD_DEP_INCLUDES "")

if (BACKEND STREQUAL "GLES2")
  find_package(GLESv2 REQUIRED)
  find_package(EGL REQUIRED)

  list(APPEND GEPARD_DEP_LIBS ${GLESv2_LIBRARY} ${EGL_LIBRARY})
  list(APPEND GEPARD_DEP_INCLUDES ${GLESv2_INCLUDE_DIR} ${EGL_INCLUDE_DIR})
elseif (BACKEND STREQUAL "VULKAN")
  find_package(Vulkan)
  list(APPEND GEPARD_DEP_INCLUDES ${VULKAN_INCLUDE_DIR})
endif ()
