set(_AVAILABLE_OPTIONS "")

macro(ADD_OPTION _name _desc _value)
  if (DEFINED ${_name})
    set(${_name}_ALREADY_DEFINED ${${_name}})
    unset(${_name} CACHE)
  endif()
  set(${_name}_VALUE ${_value})
  list(APPEND _AVAILABLE_OPTIONS ${_name})
endmacro()

function(PROCESS_OPTIONS)
  message("-- Option list:")
  foreach(_name ${_AVAILABLE_OPTIONS})
    if (DEFINED ${_name}_ALREADY_DEFINED)
      message("   - ${_name}: ${${_name}_ALREADY_DEFINED}")
      if (${${_name}_ALREADY_DEFINED})
        add_definitions("-D${_name}=${${_name}_ALREADY_DEFINED}")
      endif()
    else ()
      message("   - ${_name}: ${${_name}_VALUE}")
      if (${${_name}_VALUE})
        add_definitions("-D${_name}=${${_name}_VALUE}")
      endif()
    endif()
  endforeach()
endfunction()
